<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 2016/11/7
 * Time: 15:12
 */
namespace lbreak\datePicker;

use Yii;
use yii\web\AssetBundle;

class DatePickerAsset extends AssetBundle
{
    public $sourcePath = '@lbreak';
    public $css = [
        'asset/css/daterangepicker.css',
    ];
    public $js = [
        'asset/js/moment.js',
        'asset/js/daterangepicker.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    { 
        Yii::setAlias('@lbreak',__DIR__);
        parent::init(); // TODO: Change the autogenerated stub
    }
}